### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by richardfriedman** [ubikloadpack/jmeter#21]
Trying to build 

Just to confirm I am on this branch
- UBIKLOADPACK_REPORT_DASHBOARD_DONATION                8961c58 Resolves #20

Build steps 
ant download_jars
ant compile 

compile-core:
    [javac] Compiling 469 source files to /Users/rfriedman/com.github/ubikmeter/build/core
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /Users/rfriedman/com.github/ubikmeter/src/core/org/apache/jmeter/report/config/ReportGeneratorConfiguration.java:30: error: package com.sun.org.apache.xalan.internal.utils does not exist
    [javac] import com.sun.org.apache.xalan.internal.utils.Objects;
    [javac]                                               ^

Looking at https://github.com/apache/xalan-j/tree/xalan-j_2_7_x  I do not see Objects in the source tree.  
Is this something on me? or is this something in the build.

**Comment by ubikloadpack** [comment]
Hi Richard,
It's a bug introduced by issue #20 . 
We'll fix it in few minutes.
Thanks for report.
Regards

**Comment by ubikfsabbe** [comment]
Wrong import from me.
