### ISSUE TITLE
user.properties 

### ISSUE THREAD

**Issue by richardfriedman** [ubikloadpack/jmeter#22]
https://github.com/ubikloadpack/jmeter/blob/UBIKLOADPACK_REPORT_DASHBOARD_DONATION/bin/user.properties

Looks like user.properties is for a specific individual. 

With this in place could not get it to run against my .jtl files.

**Comment by ubikfsabbe** [comment]
I cleaned user.properties and added support of lack of graph definition.
So now with the default jmeter.properties and user.properties file, the generated graphs are empty.
You must still define the graphs in your own files.
Read [the manual](http://ubikloadpack.com/donations/dashboard/docs/usermanual/generating-dashboard.html) for configuration details.
