### ISSUE TITLE
Create an interface for SampleSource

### ISSUE THREAD

**Issue by ubikfsabbe** [ubikloadpack/jmeter#28]
We should provide an interface for SampleSource in order to allow alternates implementations

**Comment by ubikloadpack** [comment]
@ubikfsabbe 
Shouldn't instanciation be made external, ie:
instead of new CsvSampleSource, use a factory or a property for className ?

**Comment by ubikfsabbe** [comment]
@ubikloadpack 
It should be, but this issue does not cover the whole of this improvement.
It's just a preparatory task.
