### ISSUE TITLE
Allow filtering of samplers after computation

### ISSUE THREAD

**Issue by ubikloadpack** [ubikloadpack/jmeter#32]
Today filtering of samplers occurs too early and can impact the results.
Some reports require presence of all samplers (Hits per second, response code per second) .

So we need to be able to filter on some "business" samplers to present only meaningful transactions to business (not technical ones). In order to do so, we need a "presentation filter".

**Comment by ubikfsabbe** [comment]
I have just commited a first filter method. Set  jmeter.reportgenerator.exporter.html.property.show_controllers_only=true to test it.
This method has limitation with ResponseTimePerSampleGraphConsumer.
I'm working on an alternate method using filtering on series label.
Both methods can coexist : the latter implies the user knows which samples (name) he wants to filter, the former does not.

**Comment by ubikfsabbe** [comment]
Not resolved, I have forgotten to apply filter to dashboard tables.

**Comment by ubikloadpack** [comment]
Hi @ubikfsabbe ,
It's not working for me.
Also documentation has not been updated.

I have set:
<code>
jmeter.reportgenerator.exporter.html.filters_only_sample_series=true
jmeter.reportgenerator.exporter.html.series_filter=AddToCart,Category,CheckProductAvailbility,ClickCnCShipping,ClickHomeDelivery,ClickProductDetail,ClickSearch,ConfirmCnCDeliveryAddress,ConfirmDeliveryAddress,ConfirmHomeDeliveryAddress,FinalizeCnCOrder,FinalizeHomeOrder,FinalizeWebOrder,HP,HPAndGeoloc,LoginProcess,ProductList,SearchAutoComplete,ViewCart,clickCreateAccount,clickLoginLink,loginFormValidation,validateAccountCreation
</code>

or 
<code>
jmeter.reportgenerator.exporter.html.filters_only_sample_series=false
jmeter.reportgenerator.exporter.html.series_filter=AddToCart,Category,CheckProductAvailbility,ClickCnCShipping,ClickHomeDelivery,ClickProductDetail,ClickSearch,ConfirmCnCDeliveryAddress,ConfirmDeliveryAddress,ConfirmHomeDeliveryAddress,FinalizeCnCOrder,FinalizeHomeOrder,FinalizeWebOrder,HP,HPAndGeoloc,LoginProcess,ProductList,SearchAutoComplete,ViewCart,clickCreateAccount,clickLoginLink,loginFormValidation,validateAccountCreation
</code>

I get empty graphs and only total.

**Comment by ubikfsabbe** [comment]
@ubikloadpack 
series_filter expects a regular expression.
Try this :

jmeter.reportgenerator.exporter.html.filters_only_sample_series=true jmeter.reportgenerator.exporter.html.series_filter=(AddToCart)|(Category)|(CheckProductAvailbility)|(ClickCnCShipping)|(ClickHomeDelivery)|(ClickProductDetail)|(ClickSearch)|(ConfirmCnCDeliveryAddress)|(ConfirmDeliveryAddress)|(ConfirmHomeDeliveryAddress)|(FinalizeCnCOrder)|(FinalizeHomeOrder)|(FinalizeWebOrder)|(HP)|(HPAndGeoloc)|(LoginProcess)|(ProductList)|(SearchAutoComplete)|(ViewCart)|(clickCreateAccount)|(clickLoginLink)|(loginFormValidation)|(validateAccountCreation)

**Comment by ubikloadpack** [comment]
@ubikfsabbe thanks , will do.
Can you update documentation with an example ?

Thanks

**Comment by ubikloadpack** [comment]
It works with regex.
Can you mention in documentation which graphs/tables are impacted by filters also.
Thanks
